version: '3.7'

services:
  visitbooker-frontend:
    image: visitbooker-frontend:latest
    networks:
      - overlay
    ports:
      - '4000:80'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  overlay: